default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: root
  password: root
  port: 5432
  database: desconto_inss_development

test:
  <<: *default
  host: localhost
  username: root
  password: root
  port: 5432
  database: desconto_inss_test

production:
  <<: *default
  database: desconto_inss_production
  username: root
  password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
